apiVersion: apps/v1
kind: Deployment
metadata:
  name: asterin-world-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asterin-world-frontend
  template:
    metadata:
      labels:
        app: asterin-world-frontend
    spec:
      containers:
      - name: asterin-world-frontend
        image: 205930639076.dkr.ecr.ap-south-1.amazonaws.com/asterin-world-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: asterin-world-frontend-service
spec:
  selector:
    app: asterin-world-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
